import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import * as React from "react";
import { Suspense } from "react";
import Loading1 from "./Loading1"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">    
      <body className={inter.className}>
        <Suspense fallback={<Loading1/>} >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
